# Generated by Django 2.1.15 on 2020-04-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date']},
        ),
    ]
